name: Deploy Tutorials to Production Web Server

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: Build and deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          path: source

      - uses: nicholasphair/sphinx-action@7.0.0
        with:
          docs-folder: "source/tutorials/"
          # required by #1291
          pre-build-command: "apt-get update -y && apt-get install -y git && pip install myst-parser -y && echo 'extensions = [\'myst_parser\',]' > conf.py"
          build-command: "sphinx-build . ../../build/en/latest -W -D version=latest"

      - name: Deploy to staging webserver via rsync
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete --no-perms --no-owner --no-group --omit-dir-times
          path: build/en/latest/
          remote_path: /var/www/tutorials.inductiva.ai/
          remote_host: ${{secrets.STAGING_SERVER}}
          remote_user: inductiva-bot
          remote_key: ${{secrets.STAGING_WEB_SSH_KEY}}
